---
port: 8081
rackup: api.ru
timeout: 30
wait: 30
log: log/thin.log
pid: tmp/pids/thin.pid
max_conns: 1024
environment: staging
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true